 name: First workflow
 on: workflow_dispatch
 jobs:
   first_job:
     runs-on: ubuntu-latest
     steps:
       - name: Print greetings
         run: echo "hello man"
       - name: Print goodbye
         run: echo "Bye man"
